POST http://127.0.0.1:5000/api/house
Content-Type: application/json

{ "address": "1 Broadway Ave", "currentValue": 100, "loanAmount": 40 }

###

GET http://127.0.0.1:5000/api/house/14
Content-Type: application/json

###

PUT http://127.0.0.1:5000/api/house/21
Content-Type: application/json

{ "currentValue": 70, "loanAmount": 60 }