POST http://127.0.0.1:5000/api/house
Content-Type: application/json

{ "address": "1 Broadway Ave", "currentValue": 100, "loanAmount": 1000, "risk": 0.5 }

###

GET http://127.0.0.1:5000/api/house/1234
Content-Type: application/json
